# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('code', models.CharField(blank=True, max_length=225, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('comments', models.IntegerField(default=0)),
            ],
        ),
    ]
